name: build client

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-clients:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
        
    - name: Create Artifacts Directories
      run: mkdir .\Artifacts\ReleaseClient & mkdir .\Artifacts\DebugClient
      shell: cmd
      
    - name: Build Release Client
      run: 1_Build_Client_Release.bat
      shell: cmd
      working-directory: ./BuildScripts
      
    - name: Archive Release Client
      run: Get-ChildItem -Path "./Compiled/*" -Recurse | Move-Item -Destination "./Artifacts/ReleaseClient"
      
    - name: Build Debug Client
      run: 0_Build_Client_Debug.bat
      shell: cmd
      working-directory: ./BuildScripts

    - name: Archive Debug Client
      run: Get-ChildItem -Path "./Compiled/*" -Recurse | Move-Item -Destination "./Artifacts/DebugClient"

    - uses: actions/upload-artifact@v2
      name: Upload Artifacts
      with:
        name: artifacts
        path: ./Artifacts
